Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -31,7 +31,17 @@ jobs:
         cat docker-compose.yml
         docker-compose -f docker-compose.yml up -d
     - name: Wait for Agent to Register
-      working-directory: .
       run: |
-        chmod +x wait_for_agent.sh
-        sh ./wait_for_agent.sh
+          trap 'kill $(jobs -p)' EXIT
+          attempt_counter=0
+          max_attempts=45
+          mkdir -p build/reports/agent
+          docker-compose -f docker-compose.yml logs -f | tee build/reports/agent/log.txt&
+          until curl -s http://localhost:8585/api/status | jq '.registered' | grep true; do
+            if [ ${attempt_counter} -eq ${max_attempts} ]; then
+              echo "Agent failed to register. Terminating..."
+              exit 1
+            fi
+            attempt_counter=$(($attempt_counter+1))
+            sleep 1
+          done
